parameters:
#    registro.example.class: Concurso\RegistroBundle\Example

services:
    login_listener:
        class: Concurso\RegistroBundle\Listener\LoginListener
        scope: container
        arguments: [@security.context, @router]
        tags:
            - { name: kernel.event_listener, event: security.interactive_login }
            - { name: kernel.event_listener, event: kernel.response }
