parameters:
#    registro.example.class: Concurso\RegistroBundle\Example

services:
#    registro.example:
#        class: %registro.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
