concurso_estaticas_homepage:
    pattern:  /inicio/
    defaults: { _controller: ConcursoEstaticasBundle:Estaticas:index }
inicio:
    pattern: /
    defaults: { _controller: FrameworkBundle:Redirect:redirect,route: concurso_estaticas_homepage, permanent: true }
convocatoria:
    pattern:  /convocatoria/
    defaults: { _controller: ConcursoEstaticasBundle:Estaticas:convocatoria }
programa:
    pattern:  /programa/
    defaults: { _controller: ConcursoEstaticasBundle:Estaticas:programa }
ejemplos:
    pattern:  /ejemplos/
    defaults: { _controller: ConcursoEstaticasBundle:Estaticas:ejemplos }

registro:
    pattern:  /registro
    defaults: { _controller: ConcursoEstaticasBundle:Estaticas:registro }
galeria:
    pattern:  /galeria
    defaults: { _controller: ConcursoEstaticasBundle:Estaticas:galeria }
contactos:
    pattern:  /contactos/
    defaults: { _controller: ConcursoEstaticasBundle:Estaticas:contactos }
login:
    pattern:  /login/
    defaults: { _controller: RegistroBundle:Usuario:login }
login_check:
    pattern:  /login_check
logout:
    pattern:  /logout

usuario_new:
    pattern:  /usuarioNuevo
    defaults: { _controller: RegistroBundle:Usuario:new }