parameters:
#    concurso_estaticas.example.class: Concurso\EstaticasBundle\Example

services:
#    concurso_estaticas.example:
#        class: %concurso_estaticas.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
