security:
    encoders:
        concurso\RegistroBundle\Entity\Usuario:          { algorithm: sha512, iterations: 10 }
        Symfony\Component\Security\Core\User\User: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        usuarios:
            entity: { class: Concurso\RegistroBundle\Entity\Usuario, property: email }
        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        #dev:
         #   pattern:  ^/(_(profiler|wdt)|css|images|js)/
          #  security: false

        login:
            pattern:  ^/registro
            provider:       usuarios
            anonymous:      ~
            form_login:
                login_path: registro_login
                check_path: registro_login_check
            logout:
                path:       registro_logout
            remember_me:
                key:        concurso1234
                lifetime:   604800 

        #secured_area:
         #   pattern:    ^/demo/secured/
          #  form_login:
           #     check_path: _security_check
            #    login_path: _demo_login
            #logout:
             #   path:   _demo_logout
              #  target: _demo
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/singUp, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/registro, roles: ROLE_USUARIO, requires_channel: https }
