security:
    encoders:
        concurso\RegistroBundle\Entity\Usuario: { algorithm: sha512, iterations: 10 }

        Symfony\Component\Security\Core\User\User: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        usuarios:
            entity: { class: Concurso\RegistroBundle\Entity\Usuario, property: email }

    firewalls:
        registro:
            provider: usuarios
            pattern:  ^/(registro|login|login_check|logout|equipo|alumno)
            anonymous:      ~
            form_login:
                login_path: login
                check_path: login_check
                remember_me: true
            logout:
                path: /logout


    access_control:
        - { path: ^/registro, roles: ROLE_USER }
        - { path: ^/equipo, roles: ROLE_USER }

